#!/usr/bin/env python3
try:
    import bottle
except ImportError:
    bottle = None
import sys

from sweetpotato.sweetpotato.common import DAEMON_PY3K_ERROR, NO_BOTTLEPY_ERROR
from sweetpotato.sweetpotato.system import error_and_die
try:
    from sweetpotato.sweetpotato.daemon import run_daemon
except ImportError:
    error_and_die(DAEMON_PY3K_ERROR)


if __name__ == '__main__':
    if bottle:
        sys.exit(run_daemon())
    else:
        error_and_die(NO_BOTTLEPY_ERROR)
